kind: pipeline
#type: docker
type: kubernetes
name: build-and-deploy

#namespace: drone-ci

platform:
  os: linux
  arch: amd64
#
#trigger:
#  branch:
#    - main


steps:
  - name: install-deps
#    namespace: drone-ci
    image: node:18
    commands:
#      - npm install
      - git clone https://github.com/blegas78/live-sleigh.git
      - cd live-sleigh
#      - git checkout kafka


  - name: build-image
    image: plugins/docker
    settings:
      repo: docker.mogi.io/live-sleigh
      platform: linux/amd64
      tags:
#        - latest
        - ${DRONE_COMMIT_SHA}
      registry: docker.mogi.io
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD

      

  - name: update-k8s-manifests
    image: alpine/git
#    image: mikefarah/yq:4
    environment:
      GIT_AUTHOR_NAME: "blegas78"
      GIT_AUTHOR_EMAIL: "12centdwarf@gmail.com"
#    environment:
      GITHUB_PUSH_TOKEN:
        from_secret: GITHUB_PUSH_TOKEN
    commands:
      - apk add --no-cache curl
      - curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/bin/yq
      - chmod +x /usr/bin/yq
      - git config --global user.name $GIT_AUTHOR_NAME
      - git config --global user.email $GIT_AUTHOR_EMAIL
      - git clone https://$GITHUB_PUSH_TOKEN@github.com/blegas78/k8s-manifests-repo.git
      - cd k8s-manifests-repo
      - yq eval '.spec.template.spec.containers[0].image = "docker.mogi.io/live-sleigh:${DRONE_COMMIT_SHA}"' -i staging/sleigh/deployment.yaml
      - yq eval '.spec.template.spec.containers[0].image = "docker.mogi.io/live-sleigh:${DRONE_COMMIT_SHA}"' -i prod/sleigh/deployment.yaml
#      - sed -i "s|^\( *\)image: .*|\1image: docker.mogi.io/liveview:${DRONE_COMMIT_SHA}|" deployment.yaml
      

#      - sed -i "s|image: docker.mogi.io/liveview:.*|image: docker.mogi.io/liveview:${DRONE_COMMIT_SHA}|" deployment.yaml
      - git commit -am "Update image to ${DRONE_COMMIT_SHA}"
      - git push https://$GITHUB_PUSH_TOKEN@github.com/blegas78/k8s-manifests-repo.git HEAD:main
      

